theme: jekyll-theme-minimal
title: Mohamed Yahya SOALI
description: Third year student at Ecole Polytechnique - Applied Mathematics
logo: https://github.com/m-yahyaS/SOALI_website/blob/gh-pages/capture_m-yahya.jpg
